# Site
repository: artemkaxboy/PP
favicon: images/favicon.ico

# Personal info
name: Artem Kolin
title: Middle Java/Kotlin Backend Developer
email: artemkaxboy@gmail.com
website: github.com/artemkaxboy

# Social links
# twitter_username: facespics
github_username: artemkaxboy
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: artem-kolin-15084162
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Artem and I'm a middle Java/Kotlin backend developer. As well as backend developing I also have experience in teamleading and mobile apps making. I have worked at a few companies on a number of projects gaining teamwork, neotiation and leadership skills.

  I am most skilled in: <mark>Kotlin</mark> and <mark>Troubleshooting</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
